=== mantevian/planner/planner.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="plan" type="plan">
		<xs:key name="template-key">
			<xs:selector xpath="./defs/template" />
			<xs:field xpath="@name" />
		</xs:key>

		<xs:keyref name="template-ref" refer="template-key">
			<xs:selector xpath="./flat/features/furniture" />
			<xs:field xpath="@name" />
		</xs:keyref>

		<xs:unique name="unique-flat-id">
			<xs:selector xpath="flat" />
			<xs:field xpath="@id" />
		</xs:unique>
	</xs:element>

	<xs:simpleType name="metric-size">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+(\.\d+)?(mm|cm|dm|m)"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="plan">
		<xs:sequence>
			<xs:element name="defs" type="defs" maxOccurs="1" />
			<xs:element name="axes" type="axes" maxOccurs="1">
				<xs:unique name="unique-axis-id">
					<xs:selector xpath="axis" />
					<xs:field xpath="@id" />
				</xs:unique>
			</xs:element>
			<xs:element name="walls" type="walls" maxOccurs="1" />
			<xs:element name="flat" type="flat" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="defs">
		<xs:sequence>
			<xs:element name="color" type="color" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="template" type="template" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="color">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="template">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="path">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value=".*\.svg" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="axes">
		<xs:sequence>
			<xs:element name="axis" type="axis" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="axis">
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="horizontal"></xs:enumeration>
					<xs:enumeration value="vertical"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="offset" type="metric-size" />
	</xs:complexType>

	<xs:complexType name="flat">
		<xs:sequence>
			<xs:element name="features" type="features" minOccurs="0" maxOccurs="1" />
			<xs:element name="room" type="room" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>

		<xs:attribute name="id" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="room">
		<xs:sequence>
			<xs:element name="walls" type="walls" minOccurs="0" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="area_override" type="xs:double" default="0.0" />
		<xs:attribute name="area_offset_x" type="metric-size" default="0mm" />
		<xs:attribute name="area_offset_y" type="metric-size" default="0mm" />
		<xs:attribute name="not_living" type="xs:anySimpleType" default="" />
		<xs:attribute name="balcony" type="xs:anySimpleType" default="" />
	</xs:complexType>

	<xs:complexType name="walls">
		<xs:sequence>
			<xs:element name="wall" type="wall" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="wall">
		<xs:attribute name="from" type="xs:string" />
		<xs:attribute name="to" type="xs:string" />
		<xs:attribute name="thickness" type="metric-size" />
	</xs:complexType>

	<xs:complexType name="features">
		<xs:sequence>
			<xs:element name="window" type="window" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="door" type="door" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="furniture" type="furniture" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="door">
		<xs:attribute name="wall" type="xs:string" />
		<xs:attribute name="offset" type="metric-size" />
		<xs:attribute name="width" type="metric-size" />
		<xs:attribute name="side" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="window">
		<xs:attribute name="wall" type="xs:string" />
		<xs:attribute name="offset" type="metric-size" />
		<xs:attribute name="width" type="metric-size" />
	</xs:complexType>

	<xs:complexType name="furniture">
		<xs:attribute name="wall" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="width" type="metric-size" />
		<xs:attribute name="offset" type="metric-size" />
		<xs:attribute name="offset_normal" type="metric-size" />
	</xs:complexType>
</xs:schema>

=== mantevian/planner/input1.xml
<plan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="planner.xsd">
	<defs>
		<color name="wall" value="black" />
		<color name="floor" value="#cccccc" />

		<template name="door" path="door.svg" />
		<template name="window" path="window.svg" />
		<template name="chair" path="chair.svg" />
		<template name="closet" path="closet_medium.svg" />
		<template name="couch" path="couch.svg" />
		<template name="table" path="table_rectangle.svg" />
	</defs>

	<axes>
		<axis id="1" type="vertical" />
		<axis id="2" type="vertical" offset="2.5m" />
		<axis id="3" type="vertical" offset="4m" />

		<axis id="a" type="horizontal" />
		<axis id="b" type="horizontal" offset="3m" />
		<axis id="c" type="horizontal" offset="5m" />
	</axes>

	<flat id="1">
		<features>
			<window wall="1 a, 2 a" offset="2m" width="2m" />
			<door wall="2 c, 2 b" offset="1m" width="0.8m" />
			<furniture wall="1 c, 1 a" name="couch" offset="1.5m" width="1.5m" />
			<furniture wall="1 c, 1 a" name="closet" offset="3.5m" width="1.5m" />
			<furniture wall="1 c, 1 a" name="chair" offset="3.5m" offset_normal="2m" width="0.7m" />
			<furniture wall="3 a, 3 b" name="table" offset="1.5m" width="1.5m" />
		</features>

		<room>
			<walls>
				<wall from="1 a" to="3 a" thickness="0.4m" />
				<wall to="3 b" thickness="0.15m" />
				<wall to="2 b" thickness="0.15m" />
				<wall to="2 c" thickness="0.15m" />
				<wall to="1 c" thickness="0.15m" />
				<wall thickness="0.15m" />
			</walls>
		</room>
	</flat>
</plan>
